import { test } from "node:test";
import assert from "node:assert/strict";
import { bradleyTerry, judgeAgreement, kendallTau } from "../src/rank.js";
import { mulberry32 } from "../src/prng.js";

function syntheticResults(strengths, nGames, seed = 1) {
  // strengths: {id: p}. Generate nGames comparisons over random pairs with
  // outcomes drawn from the exact Bradley-Terry model.
  const rand = mulberry32(seed);
  const ids = Object.keys(strengths);
  const results = [];
  for (let g = 0; g < nGames; g++) {
    const i = Math.floor(rand() * ids.length);
    let j = Math.floor(rand() * (ids.length - 1));
    if (j >= i) j++;
    const a = ids[i];
    const b = ids[j];
    const pA = strengths[a] / (strengths[a] + strengths[b]);
    const aWins = rand() < pA;
    results.push({
      judge: `judge-${(g % 4) + 1}`,
      winner: aWins ? a : b,
      loser: aWins ? b : a,
    });
  }
  return results;
}

test("recovers ordering from synthetic data generated by known strengths", () => {
  const truth = { A: 16, B: 8, C: 4, D: 2, E: 1 };
  const results = syntheticResults(truth, 600, 42);
  const { ranking, converged } = bradleyTerry(results);

  assert.equal(converged, true);
  const trueOrder = Object.keys(truth); // already sorted by strength desc
  const recovered = ranking.map((r) => r.id);
  // Allow ties tolerance: require near-perfect Kendall tau rather than exact order.
  assert.ok(
    kendallTau(trueOrder, recovered) >= 0.8,
    `tau too low: ${kendallTau(trueOrder, recovered)} (recovered ${recovered.join(">")})`
  );
});

test("recovered strengths approximate true strength ratios", () => {
  const truth = { A: 9, B: 3, C: 1 };
  const results = syntheticResults(truth, 3000, 7);
  const { strengths } = bradleyTerry(results, { epsilon: 0.1 });
  const ratioAB = strengths.A / strengths.B;
  assert.ok(ratioAB > 1.8 && ratioAB < 5, `A/B ratio ${ratioAB} not near 3`);
  const ratioBC = strengths.B / strengths.C;
  assert.ok(ratioBC > 1.8 && ratioBC < 5, `B/C ratio ${ratioBC} not near 3`);
});

test("regularization keeps undefeated and never-winning items finite", () => {
  // X wins everything, Z loses everything — without regularization the MLE
  // sends X to +inf and Z to 0.
  const results = [
    { judge: "j1", winner: "X", loser: "Y" },
    { judge: "j1", winner: "X", loser: "Z" },
    { judge: "j2", winner: "X", loser: "Y" },
    { judge: "j2", winner: "Y", loser: "Z" },
  ];
  const { strengths, ranking, converged } = bradleyTerry(results);
  assert.equal(converged, true);
  for (const p of Object.values(strengths)) {
    assert.ok(Number.isFinite(p) && p > 0, `strength ${p} not finite/positive`);
  }
  assert.deepEqual(ranking.map((r) => r.id), ["X", "Y", "Z"]);
  assert.ok(strengths.X < 1000, "undefeated item should not blow up");
  assert.ok(strengths.Z > 1e-6, "never-winning item should not collapse to 0");
});

test("converges within maxIterations and reports iteration count", () => {
  const truth = { A: 4, B: 2, C: 1, D: 0.5 };
  const results = syntheticResults(truth, 300, 3);
  const fit = bradleyTerry(results, { tolerance: 1e-10, maxIterations: 5000 });
  assert.equal(fit.converged, true);
  assert.ok(fit.iterations > 1 && fit.iterations < 5000);

  // Strengths are normalized to geometric mean 1.
  const logs = Object.values(fit.strengths).map(Math.log);
  const meanLog = logs.reduce((a, b) => a + b, 0) / logs.length;
  assert.ok(Math.abs(meanLog) < 1e-6, `geometric mean not 1 (meanLog=${meanLog})`);

  // Scores sum to 1.
  const scoreSum = fit.ranking.reduce((a, r) => a + r.score, 0);
  assert.ok(Math.abs(scoreSum - 1) < 1e-9);
});

test("confidence increases with comparison count", () => {
  const truth = { A: 8, B: 4, C: 2, D: 1 };
  const few = bradleyTerry(syntheticResults(truth, 40, 5));
  const many = bradleyTerry(syntheticResults(truth, 800, 5));
  const avg = (fit) => fit.ranking.reduce((a, r) => a + r.confidence, 0) / fit.ranking.length;
  assert.ok(avg(many) > avg(few), `expected more data => more confidence (${avg(many)} vs ${avg(few)})`);
  for (const r of many.ranking) assert.ok(r.confidence >= 0 && r.confidence < 1);
});

test("judge agreement flags a judge who votes against consensus", () => {
  const strengths = { A: 8, B: 4, C: 2, D: 1 };
  const results = [];
  // 4 sensible judges always pick the stronger project...
  for (const judge of ["j1", "j2", "j3", "j4"]) {
    for (const [w, l] of [["A","B"],["A","C"],["A","D"],["B","C"],["B","D"],["C","D"]]) {
      results.push({ judge, winner: w, loser: l });
    }
  }
  // ...and one contrarian always picks the weaker one.
  for (const [w, l] of [["B","A"],["C","A"],["D","A"],["C","B"],["D","B"],["D","C"]]) {
    results.push({ judge: "contrarian", winner: w, loser: l });
  }
  const agreement = judgeAgreement(results, strengths);
  assert.equal(agreement.j1.rate, 1);
  assert.equal(agreement.contrarian.rate, 0);
  assert.equal(agreement.contrarian.outlier, true);
  assert.equal(agreement.j1.outlier, false);
});

test("kendallTau: identical, reversed, and partial orders", () => {
  assert.equal(kendallTau(["a", "b", "c"], ["a", "b", "c"]), 1);
  assert.equal(kendallTau(["a", "b", "c"], ["c", "b", "a"]), -1);
  const tau = kendallTau(["a", "b", "c", "d"], ["a", "c", "b", "d"]);
  assert.ok(Math.abs(tau - 4 / 6) < 1e-12); // one swapped adjacent pair
});

test("rejects empty and self-comparison inputs", () => {
  assert.throws(() => bradleyTerry([]));
  assert.throws(() => bradleyTerry([{ winner: "A", loser: "A" }]));
});
